import { Component, ChangeDetectionStrategy, inject, signal } from '@angular/core';
import { ExtensionStoreService } from '../../services/extension-store.service';
import { MatIconModule } from '@angular/material/icon';

export interface OnboardingStep {
  id: number;
  title: string;
  category: string;
  description: string;
  command?: string;
  completed: boolean;
  resources: { name: string; url: string; icon: string }[];
  details: string[];
}

@Component({
  selector: 'app-onboarding-wizard',
  standalone: true,
  imports: [MatIconModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './onboarding-wizard.html'
})
export class OnboardingWizardComponent {
  store = inject(ExtensionStoreService);

  feedbackText = signal('');
  feedbackEmail = signal('');

  steps = signal<OnboardingStep[]>([
    {
      id: 1,
      title: 'Clone Monorepo & System Prerequisites',
      category: 'Environment Setup',
      description: 'Ensure Node.js v20+ and pnpm v9+ are installed, then clone the Qeloma MV3 Monorepo repository.',
      command: 'git clone https://github.com/qeloma/extensions-monorepo.git && cd extensions-monorepo',
      completed: true,
      resources: [
        { name: 'Node.js LTS Installation', url: 'https://nodejs.org', icon: 'download' },
        { name: 'pnpm Workspace Guide', url: 'https://pnpm.io/workspaces', icon: 'auto_awesome' }
      ],
      details: [
        'Requires Node.js v20.0.0 or higher for ESM and type stripping support.',
        'pnpm workspaces optimize disk usage by deduplicating shared packages.'
      ]
    },
    {
      id: 2,
      title: 'Enable pnpm & Install Workspaces',
      category: 'Dependencies',
      description: 'Enable Node corepack and run pnpm install to link all 5 shared packages and 10 extension apps.',
      command: 'corepack enable && pnpm install',
      completed: true,
      resources: [
        { name: 'PNPM Monorepo Docs', url: 'https://pnpm.io', icon: 'description' },
        { name: 'WXT Framework Setup', url: 'https://wxt.dev', icon: 'build' }
      ],
      details: [
        'Links @qeloma/types, @qeloma/ui, @qeloma/utils, @qeloma/gemini, and @qeloma/storage.',
        'Installs WXT build engine dependencies across all 10 tools simultaneously.'
      ]
    },
    {
      id: 3,
      title: 'Run Local WXT Dev Server & Hot-Reload',
      category: 'Local Development',
      description: 'Start hot-reloading dev server for a specific extension or the entire suite simultaneously.',
      command: 'pnpm dev:clip-lens # or pnpm dev:shot',
      completed: false,
      resources: [
        { name: 'WXT Extension CLI Guide', url: 'https://wxt.dev/guide/cli.html', icon: 'terminal' },
        { name: 'Chrome MV3 Dev Docs', url: 'https://developer.chrome.com/docs/extensions', icon: 'open_in_new' }
      ],
      details: [
        'WXT starts Vite on local dev port with instant HMR and background service worker re-registration.',
        'Build artifacts are output to packages/<extension-name>/.output/chrome-mv3'
      ]
    },
    {
      id: 4,
      title: 'Load Unpacked Extension in Chrome',
      category: 'Debugging & Verification',
      description: 'Open chrome://extensions in Google Chrome, enable "Developer mode", and click "Load unpacked".',
      command: 'chrome://extensions',
      completed: false,
      resources: [
        { name: 'Chrome Developer Mode Guide', url: 'https://developer.chrome.com/docs/extensions/mv3/getstarted/development-basics/', icon: 'bug_report' },
        { name: 'CWS Fast-Track Review Policy', url: 'https://developer.chrome.com/docs/webstore/review-process/', icon: 'verified' }
      ],
      details: [
        'Select the .output/chrome-mv3 folder generated by the dev build.',
        'Inspect background service worker console and test popup UI extensions.'
      ]
    },
    {
      id: 5,
      title: 'Run Pre-flight CWS Linter & Bundle Zip',
      category: 'CI/CD & Store Release',
      description: 'Run the Manifest V3 security linter and compile production-ready zip bundles for CWS submission.',
      command: 'pnpm lint:manifests && pnpm build:all',
      completed: false,
      resources: [
        { name: 'Chrome Web Store Dashboard', url: 'https://chrome.google.com/webstore/devconsole', icon: 'storefront' },
        { name: 'Qeloma CWS Compliance Report', url: '#', icon: 'assessment' }
      ],
      details: [
        'Ensures zero remote code execution, strictly valid CSP, and permission tier classification.',
        'Generates store-ready .zip archives in the /dist directory.'
      ]
    }
  ]);

  toggleStep(id: number) {
    this.steps.update(list => list.map(step => {
      if (step.id === id) {
        return { ...step, completed: !step.completed };
      }
      return step;
    }));
  }

  get completedCount() {
    return this.steps().filter(s => s.completed).length;
  }

  get progressPercentage() {
    return Math.round((this.completedCount / this.steps().length) * 100);
  }

  copyCommand(cmd?: string) {
    if (cmd && navigator.clipboard) {
      navigator.clipboard.writeText(cmd);
      this.store.submitFeedback(`Copied command: ${cmd}`);
    }
  }

  submitOnboardingFeedback(msgInput: HTMLTextAreaElement, emailInput: HTMLInputElement) {
    const msg = msgInput.value.trim();
    const email = emailInput.value.trim() || 'contributor@qeloma.dev';
    if (msg) {
      this.store.submitFeedback(msg, email, 'Onboarding Wizard');
      msgInput.value = '';
    }
  }
}
